# Site settings
title: Stack & Tier 
email: karl@stacktier.org
url: https://stacktier.org/
description: "-General consulting in information systems & technology (IoT or EoT) infrastructure planning, 1-on-1 training.
-Hardware and Software setup & support (mainly in Windows environments); hardware troubleshooting, software maintenance and testing, security, encryption, backup, and recovery.
-Network troubleshooting, setup, and maintenance.
-Smart home planning, techniques, technologies, setup, maintenance, etc.
-Software multi tenancy implementation, PaaS and network distributed versioning control implementation and auto deployment. Web development, static to dynamic sites,project hosting, API integration.
-Productivity tools; information process flow diagramming & analysis, charting & report development and solutions, local and cloud organization solutions, data collection, virtual network computing, SEO, Adwords, Google Developer Products (Charts, Scripts, Analytics, etc), mail digitization, e-commerce, financial services, authentication.
-Consumer entertainment: media management solutions, network distributed DLNA hardware, DVR software, matrix switch setup.
"
skills: "Hardware & Systems Consulting, Design, Planning, Deployment and Support."
meta_author: Erdmannn Karl

# Google webmaster tools
google_verify: wdX47nZWS271lk-dQ3V5GVwrPDQe-88d4MUI2x9P-FI

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location 
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) 
# http://fontawesome.io
#  - title: stack-overflow
#    url: http://stackexchange.com/users/3846962/user289394?tab=accounts

social:
  - title: facebook
    url: https://www.facebook.com/StackTier

  - title: github
    url: http://github.com/StackTier
  - title: yelp
    url: https://www.yelp.com/biz/stack-and-tier-seattle
  - title: check-square
    url: https://www.trustpilot.com/review/stacktier.github.io 
  - title: envelope-o
    url: mailto:karl@stacktier.org 
  - title: youtube
    url: https://www.youtube.com/channel/UCPr4Rn5wPs1llVxnu8UiAMw
  - title: phone
    url: http://www.anveo.com/contactme/small_call
  - title: comments
    url: https://m.me/StackTier
   - title: amazon
    url: https://www.amazon.com/localservices/ya/sellerprofile/ref=vas_sc_spp_A3626NNLQCERB7?sellerID=A3626NNLQCERB7
    

# Postal address (add as many lines as necessary)
address:
  - line:  
  - line: Seattle, WA

# Credits content
credits: 'This theme (Freelancer) is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. Hosted on <a href="https://pages.github.com/">GitHub</a>'

# Build settings
markdown: kramdown
permalink: pretty
